version: '3'
services:
 docker-app:
    image: bionexo/geoubs-app
    ports:
      - "8090:8080"
    depends_on:
      - docker-mysql

 docker-mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123  
